"""Init

Revision ID: 190c7b616bf3
Revises: d91c2ec3be46
Create Date: 2023-05-25 00:20:30.152625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190c7b616bf3'
down_revision = 'd91c2ec3be46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
