"""Init

Revision ID: d91c2ec3be46
Revises: 
Create Date: 2023-05-25 00:02:10.576653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c2ec3be46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('date_of', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teachers_to_students')
    op.drop_table('contacts')
    op.add_column('students', sa.Column('fullname', sa.String(length=120), nullable=False))
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('students', 'email')
    op.drop_column('students', 'address')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'phone')
    op.add_column('teachers', sa.Column('fullname', sa.String(length=120), nullable=False))
    op.drop_column('teachers', 'start_work')
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'address')
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'first_name')
    op.drop_column('teachers', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('phone', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('start_work', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'fullname')
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.drop_column('students', 'fullname')
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='contacts_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey')
    )
    op.create_table('teachers_to_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='teachers_to_students_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teachers_to_students_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teachers_to_students_pkey')
    )
    op.drop_table('grades')
    op.drop_table('disciplines')
    op.drop_table('groups')
    # ### end Alembic commands ###
